site_name: Vapus docs

theme:
  name: material
  # font: roboto
  logo: assets/logo-white.svg
  favicon: assets/logo.svg

  palette:
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: Copyright &copy; 2024 Anekam Datanet Technologies
